inherit_from: ../.rubocop.yml

require:
  - rubocop-rspec
Metrics/BlockLength:
  Enabled: false
RSpec/ExampleWithoutDescription:
  EnforcedStyle: single_line_only
RSpec/ImplicitExpect:
  EnforcedStyle: is_expected
RSpec/MessageExpectation:
  Enabled: true
  EnforcedStyle: expect
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleExpectations:
  Max: 2
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NotToNot:
  EnforcedStyle: not_to
RSpec/Pending:
  Enabled: true
RSpec/NestedGroups:
  Max: 4
